export const SET_HEADER = 'SET_HEADER';
export const SET_ACCOUNT = 'SET_ACCOUNT';
export const SET_USER_TOKEN = 'SET_USER_TOKEN';
export const SET_MD5_SALT = 'SET_MD5_SALT';
export const SET_SHOW_TIME = 'SET_SHOW_TIME';
export const SET_SHOW_PICKER = 'SET_SHOW_PICKER';
export const SET_TIP = 'SET_TIP';
export const SET_IS_DEBUGGER = 'SET_IS_DEBUGGER';
export const SET_API_BASE = 'SET_API_BASE';
export const SET_MESSAGE_COUNT = 'SET_MESSAGE_COUNT';
export const SET_HD_QIANDAO = 'SET_HD_QIANDAO';
export const SET_HD_CHARGE = 'SET_HD_CHARGE';
export const SET_HD_ZLCJ = 'SET_HD_ZLCJ';
export const SET_HD_XRKH = 'SET_HD_XRKH';
export const SET_HD_FXPYQ = 'SET_HD_FXPYQ';
export const SET_HAS_PHONE = 'SET_HAS_PHONE';
export const SET_SHOW_SEARCH = 'SET_SHOW_SEARCH';
export const SET_HREF_TYPE = 'SET_HREF_TYPE';
export const SET_USER_ID = 'SET_USER_ID';
export const SET_XGLHC_COLOR = 'SET_XGLHC_COLOR';
export const SET_NAV_ACTIVE = 'SET_NAV_ACTIVE';         //  设置添加彩种页面底部导航保留首页当前样式
export const SET_RECORD_SHOW = 'SET_RECORD_SHOW';          //  设置房间模式投注记录是否显示
export const SET_RECORD_DETAIL_SHOW = 'SET_RECORD_DETAIL_SHOW';          //  设置房间模式投注记录详情页是否显示
export const SET_RECORD_CHOOSE = 'SET_RECORD_CHOOSE'
export const SET_FOOT_SHOW = 'SET_FOOT_SHOW';          //  设置房间模式投注记录详情页是否显示
export const SET_LOADING_SHOW = 'SET_LOADING_SHOW'; 
export const SET_HEARDERADD_SHOW = 'SET_HEARDERADD_SHOW';
export const SET_MODEL_SHOW = 'SET_MODEL_SHOW';
export const SET_IOS_GOBACK = 'SET_IOS_GOBACK';
export const SET_DOWNLOAD_URL = 'SET_DOWNLOAD_URL';
export const SET_SERVER_SHOW = 'SET_SERVER_SHOW';
export const SET_HEAD_SHOW = 'SET_HEAD_SHOW';         //  设置页面头部是否隐藏
